### ISSUE TITLE
Error when running scripts

### ISSUE THREAD

**Issue by shmuelfomberg** [LaurieWired/JADXecute#12]
even when running the "Blank template", I get an error:

Jadx version : dev
Java version : 19.0.2
Java VM      : Oracle Corporation OpenJDK 64-Bit Server VM
Platform     : Windows 10 (10.0 amd64)
Max heap size: 7272 MB

java.lang.NoClassDefFoundError: javax/tools/DiagnosticListener
	at jadx.gui.plugins.jadxecute.JadxecuteDialog.executeBackgroundTask(JadxecuteDialog.java:331)
	at jadx.gui.plugins.jadxecute.JadxecuteDialog.lambda$runUserCode$4(JadxecuteDialog.java:313)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: javax.tools.DiagnosticListener
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 5 more

Running the latest (1.0.3) with the JRE that came with jadx-gui 1.4.7. 
the console output box is blank.

**Comment by shmuelfomberg** [comment]
new installation with global java installed works.
installation with local JRE didn't work.
